version: '2'
services:

  composer:
    build: ./docker/composer
    container_name: phive-composer
    volumes:
      - ./docker/composer/composer:/composer
    volumes_from:
      - plugin
    depends_on:
      - plugin
    working_dir: /app

  plugin:
    build: ./docker/plugin
    container_name: phive-plugin
    volumes:
      - ./src:/app
    working_dir: /app

  phpstan:
    image: phpstan/phpstan
    depends_on:
      - plugin
    volumes_from:
      - plugin
    working_dir: /app

  humbug:
    image: dockerizedphp/humbug
    depends_on:
      - plugin
    volumes_from:
      - plugin
    working_dir: /app

