version: '2'
services:

  composer:
    build: ./composer
    container_name: phive-composer
    volumes:
      - ./composer/composer:/composer
    volumes_from:
      - plugin
    depends_on:
      - plugin
    working_dir: /app

  plugin:
    image: php:5.6-alpine
    container_name: phive-plugin
    volumes:
      - ./plugin:/app
    working_dir: /app

  phpstan:
    image: phpstan/phpstan
    depends_on:
      - plugin
    volumes_from:
      - plugin
    working_dir: /app

  humbug:
    image: dockerizedphp/humbug
    depends_on:
      - plugin
    volumes_from:
      - plugin
    working_dir: /app

